layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap

permalink: /:categories/:title/

exclude:
  - README.md

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "google0dfe9728f2b23a92.html"
    values:
      sitemap: false
  -
    scope:
      path: "**/*.pdf"
    values:
      sitemap: false

projects:
  sort_by: stars
  limit: 8
  exclude:
    archived: true
    forks: true
    projects:
      - ookii-dialogs-winforms
      - DevExpress-NuGet
      - exceldna-addin-abstractions
      - serilog-enrichers-exceldna

social_media:
  twitter: augustoproiete
  linkedin: augustoproiete
  stackoverflow: 211672
  keybase: augustoproiete

topics:
  - name: .NET Core
    web_url: https://dotnet.microsoft.com
    image_url: https://raw.githubusercontent.com/github/explore/93d8a67084f94b2a444e510199a6e7622e5b09a3/topics/dotnet/dotnet.png

  - name: CSharp
    web_url: https://github.com/dotnet/csharplang
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/csharp/csharp.png

  - name: TypeScript
    web_url: https://www.typescriptlang.org
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png

  - name: Python
    web_url: https://www.python.org
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Rust
    web_url: https://www.rust-lang.org/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/rust/rust.png

  - name: ASP .NET Core
    web_url: https://dotnet.microsoft.com/apps/aspnet
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/aspnet/aspnet.png

  - name: React
    web_url: https://reactjs.org
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png

  - name: PostgreSQL
    web_url: https://www.postgresql.org
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/postgresql/postgresql.png

  - name: Git
    web_url: https://git-scm.com
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png

  - name: Docker
    web_url: https://www.docker.com
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Microsoft Azure
    web_url: https://azure.microsoft.com
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/azure/azure.png

  - name: Amazon Web Services
    web_url: https://aws.amazon.com
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
